import { TProduct } from '@/types/product';

export const productsData: TProduct[] = [
  {
    id: 1,
    quantity: 22970,
    path: '/products/1',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 0,
    priceWithoutDiscount: 76530000,
    priceWithDiscount: 76530000,
    title: {
      fa: 'هدست پلی استیشن سونی اسلیم مدل پالس لایت وایرلس',
      en: 'Sony PlayStation 4 Headset Model PULSD',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/13-2.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-7.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/5-7.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 2,
    quantity: 20,
    path: '/products/2',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 12,
    priceWithoutDiscount: 15200000,
    priceWithDiscount: 13400000,
    title: {
      fa: 'گوشی موبايل موتورولا مدل ادج پرو ظرفیت به همراه کارت هدیه',
      en: 'Motorola Edge Pro mobile phone One RAM with gift card',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-7.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-1.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-1.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 3,
    quantity: 43,
    path: '/products/3',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 12,
    priceWithoutDiscount: 42500000,
    priceWithDiscount: 42500000,
    title: {
      fa: 'گوشی موبایل اپل مدل آیفون 13 نات اکتیو تک سیم کارت ظرفیت 128 گیگابایت رم 4 گیگابایت',
      en: 'Apple iPhone Pro Not Active Mobile Phone Refurbish Part Number',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/1-11.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/Frame-19-1.png',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 4,
    quantity: 232,
    path: '/products/4',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 0,
    priceWithoutDiscount: 20200000,
    priceWithDiscount: 20200000,
    title: {
      fa: 'گوشی موبایل شیائومی مدل پوکو دو سیم کارت ظرفیت نات اکتیو',
      en: 'Xiaomi Poco Dual SIM And RAM Mobile Phone',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/7-5.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/6.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 5,
    quantity: 10,
    path: '/products/5',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 3,
    priceWithoutDiscount: 24200000,
    priceWithDiscount: 23400000,
    title: {
      fa: 'گوشی موبایل شیائومی مدل ردمی‌نوت دو سیم‌ کارت نات‌اکتیو',
      en: 'Xiaomi Redmi Note Dual SIM And RAM Mobile Phone',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/8-3.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/1-4.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-3.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-3.png',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 6,
    quantity: 23,
    path: '/products/6',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 3,
    priceWithoutDiscount: 24200000,
    priceWithDiscount: 23400000,
    title: {
      fa: 'لپ تاپ 13 اینچ اپل مدل مک‌بوک ایر هارد اس‌اس‌دی 500 گیگ ریجن آسیا',
      en: 'Apple MacBook Air MGB RAM GB SSD Laptop',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/1-18.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-4.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/1-5.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-4.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 7,
    quantity: 8,
    path: '/products/7',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 0,
    priceWithoutDiscount: 76530000,
    priceWithDiscount: 76530000,
    title: {
      fa: 'لپ تاپ اپل مدل مک بوک ایر مکس یک ترابایت',
      en: 'Apple MacBook Air MGN LLA GB SSD inch Laptop',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-15.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/1-3.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-2.jpg',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/3-2.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
  {
    id: 8,
    quantity: 21,
    path: '/products/8',
    attributes: [
      { key: 'رنگ', value: 'سبز' },
      { key: 'برند', value: 'اپل' },
      { key: 'دسته بندی', value: 'موبایل' },
      { key: 'اقلام همراه', value: 'شارژر' },
    ],
    discount: 0,
    priceWithoutDiscount: 10200000,
    priceWithDiscount: 10200000,
    title: {
      fa: 'لپ تاپ 14.2 اینچی اپل مدل مک بوک ایر پرو یک ترابایت',
      en: 'Apple MacBook Air MGB RAM GB SSD Laptop',
    },
    category: {
      text: 'گیمینگ و لوازم',
      path: '/explore',
      image: 'https://shopi.codisa.ir/wp-content/uploads/2024/10/Cat10-1.png',
    },
    images: [
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/7-11.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/4-7.png',
      'https://shopi.codisa.ir/wp-content/uploads/2024/10/2-4.jpg',
    ],
    description: `لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.`,
  },
];
